spring:
  application:
    name: DiscoverClient

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka server URL
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true  # shows IP instead of hostname

server:
  port: 8082
