spring:
  application:
    name: ServiceRegistry


eureka:
  client:
    register-with-eureka: false   # this server should not register itself
    fetch-registry: false         # this server does not need to fetch registry
  server:
    wait-time-in-ms-when-sync-empty: 0

server:
  port: 8761

