server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tousif67/Spring-Learning-Journey.git
          default-label: main
          clone-on-start: true
          search-paths: 07-Spring-Microservices/projects/configs/